## Example 1: Chimera

In [1]:
import dwave_networkx as dnx
import random
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
from dwave.experimental.automorphism import *

G = dnx.chimera_graph(1)

num_delete = 0
to_remove = random.sample(range(0, G.number_of_nodes()), num_delete)

for node in to_remove:
    G.remove_node(node)

# relabel nodes to be continuous
label_mapping={list(G.nodes)[j]:j for j in range(G.number_of_nodes())}
G=nx.relabel_nodes(G, label_mapping) 

pos = nx.spring_layout(G)  # positions for all nodes
nx.draw(G, pos, with_labels=True, node_color='lightgreen', node_size=100)

plt.show()

ModuleNotFoundError: No module named 'dwave.experimental.automorphism'

In [8]:
# Get the group vector in the Schreier-Sims reprsentation
G_vector_chimera = schreier_rep(G, num_samples=3)

In [12]:
#print the elements of the group vector in cycle notation (not including identity)
for i, U in enumerate(G_vector_chimera[1]):
    print(f'\nU_{i}:')
    for h in U:
        print(ArrayToCycle(h))


U_0:
(0,7,6)(1,4)(2)(3)(5)
(0,1,7,4,6,2)(3,5)
(0,2)(1,7,4,6)(3,5)
(0,3,5,4,6,1,7,2)
(0,4,7,2)(1,6)(3,5)
(0,5,7,6)(1)(2)(3)(4)
(0,6)(1,2,4)(3)(5)(7)

U_1:
(0)(1,4,2)(3)(5)(6,7)
(0)(1,2)(3)(4)(5)(6)(7)
(0)(1,3,4,2)(5)(6)(7)

U_2:
(0)(1)(2,4)(3)(5)(6,7)
(0)(1)(2,3,4)(5)(6)(7)

U_3:
(0)(1)(2)(3,4)(5)(6,7)

U_4:

U_5:
(0)(1)(2)(3)(4)(5,6)(7)
(0)(1)(2)(3)(4)(5,7)(6)

U_6:
(0)(1)(2)(3)(4)(5)(6,7)

U_7:


In [11]:
print('Number of automorphisms: ', int(np.prod([len(x) + 1 for x in G_vector_chimera[1]])))

Number of automorphisms:  1152


## Example 2: Zephyr-12 Lattice w/ 96% yield

In [2]:
import dwave_networkx as dnx
import random
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
#from dwave.experimental.automorphism import *
import sys
sys.path.append("C:\\Users\\sgitt\\source\\dwave-experimental\\dwave\\experimental\\automorphism")
from automorphism_generation import schreier_rep, array_to_cycle, mult

In [15]:
import dwave_networkx as dnx
#G_c1 = dnx.chimera_graph(4)
G_c1 = dnx.zephyr_graph(3)

result1 = schreier_rep(G_c1, num_samples=300)

leaf nodes reached:  46
total nodes reached:  1072


In [16]:
edge_orbits = result1._edge_orbits()

In [17]:
result1.edge_orbits

[[(0, 1),
  (5, 4),
  (144, 145),
  (149, 148),
  (17, 16),
  (12, 13),
  (162, 163),
  (167, 166),
  (11, 10),
  (6, 7),
  (156, 157),
  (161, 160),
  (18, 19),
  (23, 22),
  (155, 154),
  (150, 151),
  (168, 169),
  (173, 172),
  (329, 328),
  (324, 325),
  (186, 187),
  (191, 190),
  (323, 322),
  (318, 319),
  (180, 181),
  (185, 184),
  (317, 316),
  (312, 313),
  (330, 331),
  (335, 334),
  (179, 178),
  (174, 175)],
 [(0, 3),
  (5, 2),
  (144, 147),
  (149, 146),
  (17, 14),
  (12, 15),
  (162, 165),
  (167, 164),
  (11, 8),
  (6, 9),
  (156, 159),
  (161, 158),
  (18, 21),
  (23, 20),
  (155, 152),
  (150, 153),
  (168, 171),
  (173, 170),
  (329, 326),
  (324, 327),
  (186, 189),
  (191, 188),
  (323, 320),
  (318, 321),
  (180, 183),
  (185, 182),
  (317, 314),
  (312, 315),
  (330, 333),
  (335, 332),
  (179, 176),
  (174, 177)],
 [(0, 192),
  (0, 210),
  (0, 198),
  (0, 204),
  (5, 288),
  (144, 209),
  (149, 305),
  (17, 288),
  (12, 192),
  (162, 209),
  (167, 305),
  (11

In [11]:
G_z = dnx.zephyr_graph(12)
#G_z = dnx.chimera_graph(1)
#G_z = dnx.zephyr_graph(2)

num_delete = int(0.04 * G_z.number_of_nodes())
#num_delete = 0
random.seed(43)
to_remove = random.sample(range(0, G_z.number_of_nodes()), num_delete)

for node in to_remove:
    G_z.remove_node(node)

# relabel nodes to be continuous
label_mapping = {list(G_z.nodes)[j]:j for j in range(G_z.number_of_nodes())}
G_z = nx.relabel_nodes(G_z, label_mapping) 

In [4]:
to_remove

[]

In [5]:
G_vector_zephyr = schreier_rep(G_z, num_samples=500) # takes about 5 mins #190210142896128
G_vector_zephyr.num_automorphisms

leaf nodes reached:  8
total nodes reached:  34


1152

In [12]:
import cProfile
cProfile.run('G_vector_zephyr = schreier_rep(G_z, num_samples=500)')

leaf nodes reached:  31
total nodes reached:  496
         175603281 function calls (175440674 primitive calls) in 155.688 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.000    0.000    0.000    0.000 <frozen abc>:121(__subclasscheck__)
        3    0.000    0.000    0.000    0.000 <frozen importlib._bootstrap>:1390(_handle_fromlist)
        1    0.001    0.001  155.650  155.650 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 <string>:2(__init__)
   311799    0.076    0.000    0.535    0.000 _methods.py:58(_any)
   173293    0.043    0.000    0.297    0.000 _methods.py:67(_all)
        1    0.000    0.000    0.001    0.001 asyncio.py:206(_handle_events)
        1    0.000    0.000    0.000    0.000 asyncio.py:216(call_at)
        3    0.000    0.000    0.000    0.000 attrsettr.py:43(__getattr__)
        3    0.000    0.000    0.000    0.000 attrsettr.py:66(_get_attr_opt)
   173682    3.714

CFI

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

nodes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
edges = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 0), (0, 3), (1, 4), (2, 6), (5, 7)]

G1 = nx.Graph()
G1.add_nodes_from(nodes)
G1.add_edges_from(edges)

layout = nx.shell_layout(G1)  # You can also try nx.shell_layout(G), nx.spring_layout(G), etc.

plt.figure(figsize=(2, 2))  # set figure size here
nx.draw(G1, with_labels=True, pos=layout, node_color='lightgreen', edge_color='gray', node_size=300, font_size=14)
plt.show()

In [18]:
G_vector_zephyr.sample_automorphisms(20)

[array([2, 0, 3, 1, 6, 7, 5, 4]),
 array([0, 1, 3, 2, 7, 5, 4, 6]),
 array([1, 0, 3, 2, 4, 7, 5, 6]),
 array([0, 1, 3, 2, 5, 7, 6, 4]),
 array([2, 3, 0, 1, 6, 4, 7, 5]),
 array([3, 2, 0, 1, 7, 5, 6, 4]),
 array([7, 4, 6, 5, 0, 1, 3, 2]),
 array([4, 7, 6, 5, 0, 3, 2, 1]),
 array([0, 1, 3, 2, 7, 5, 4, 6]),
 array([5, 4, 7, 6, 0, 3, 1, 2]),
 array([7, 6, 4, 5, 0, 3, 2, 1]),
 array([1, 0, 3, 2, 5, 4, 6, 7]),
 array([3, 2, 0, 1, 6, 5, 4, 7]),
 array([5, 4, 6, 7, 0, 3, 1, 2]),
 array([6, 5, 7, 4, 0, 1, 3, 2]),
 array([5, 6, 4, 7, 0, 3, 2, 1]),
 array([4, 5, 7, 6, 0, 3, 1, 2]),
 array([7, 6, 5, 4, 0, 2, 3, 1]),
 array([1, 0, 3, 2, 6, 7, 4, 5]),
 array([4, 7, 5, 6, 0, 1, 3, 2])]

In [9]:
5435817984

5435817984

In [10]:
result = G_vector_zephyr

In [11]:
print('Schreier-Sims representation (not including identity):')
for i in sorted(result.u_map.keys()):
    print(f'U_{i}:')
    for h in result.u_vector[result.u_map[i]]:
        print(array_to_cycle(h))

Schreier-Sims representation (not including identity):
U_0:
(0,1)(2)(3)(4)(5)(6)(7)
(0,3,2,1)(4)(5)(6)(7)
(0,2)(1,3)(4)(5)(6)(7)
(0,4)(1,5)(2,6)(3,7)
(0,5,1,4)(2,6)(3,7)
(0,7,3,6,2,4)(1,5)
(0,6,2,5,1,7,3,4)
U_1:
(0)(1,2)(3)(4)(5)(6)(7)
(0)(1,3)(2)(4)(5)(6)(7)
U_2:
(0)(1)(2,3)(4)(5)(6)(7)
U_4:
(0)(1)(2)(3)(4,6,5,7)
(0)(1)(2)(3)(4,5)(6,7)
(0)(1)(2)(3)(4,7,5,6)
U_5:
(0)(1)(2)(3)(4)(5,7)(6)
(0)(1)(2)(3)(4)(5,6)(7)
U_6:
(0)(1)(2)(3)(4)(5)(6,7)


In [222]:
U_count = []
for i in sorted(result.u_map.keys()):
    U_count.append(len(result.u_vector[result.u_map[i]]))
U_count

[7, 3, 2, 1, 2, 1]

In [207]:
np.random.randint(5)

4

In [223]:
import numpy as np
rng = np.random.default_rng(42)

def sample_automorphism(result, num_samples):
    U_count = []
    for i in sorted(result.u_map.keys()):
        U_count.append(len(result.u_vector[result.u_map[i]]))

    highs = np.array(U_count)

    samples = rng.integers(low=0, high=highs + 1)

    samples

In [231]:
highs = np.array(U_count)

samples = rng.integers(low=-1, high=highs)

samples

array([ 4,  0, -1,  0,  0,  0])

In [ ]:
def sample_automorphism(result, num_samples):
    u_count = []
    for i in sorted(result.u_map.keys()):
        u_count.append(len(result.u_vector[result.u_map[i]]))
    automorphisms = []
    for _ in range(num_samples):
        samples = rng.integers(low=-1, high=u_count)
        last_g = result.identity
        for i, key in enumerate(sorted(result.u_map.keys())):
            if samples[i] >= 0:
                g = result.u_vector[result.u_map[key]][samples[i]]
                last_g = mult(g, last_g)
        automorphisms.append(last_g)
    return automorphisms

In [288]:
res = sample_automorphism(result, 100000)

In [268]:
for g in res:
    print(array_to_cycle(g))

(0)(1)(2)(3)(4)(5)(6)(7)(8)(9)(10)(11)(12)(13)(14)(15)(16)(17)(18)(19)(20)(21)(22)(23)(24)(25)(26)(27)(28)(29)(30)(31)(32)(33)(34)(35)(36)(37)(38)(39)(40)(41)(42)(43)(44)(45)(46)(47)(48)(49)(50)(51)(52)(53)(54)(55)(56)(57)(58)(59)(60)(61)(62)(63)(64)(65)(66)(67)(68)(69)(70)(71)(72)(73)(74)(75)(76)(77)(78)(79)(80)(81)(82)(83)(84)(85)(86)(87)(88)(89)(90)(91)(92)(93,162)(94,163)(95,164)(96,165)(97,166)(98,167)(99,168)(100,169)(101,170)(102,171)(103,172)(104,173)(105,174)(106,175)(107,176)(108,177)(109,178)(110,179)(111,180)(112,181)(113,182)(114,183)(115,184)(116,185)(117)(118)(119)(120)(121)(122)(123)(124)(125)(126)(127)(128)(129)(130)(131)(132)(133)(134)(135)(136)(137)(138)(139)(140)(141)(142)(143)(144)(145)(146)(147)(148)(149)(150)(151)(152)(153)(154)(155)(156)(157)(158)(159)(160)(161)(186)(187)(188)(189)(190)(191)(192)(193)(194)(195)(196)(197)(198)(199)(200)(201)(202)(203)(204)(205)(206)(207)(208)(209)(210)(211)(212)(213)(214)(215)(216)(217)(218)(219)(220)(221)(222)(223)(224)(225)(226

In [139]:
for sample in samples:
    if sample >= 0:
        print(result.u_vector[sample])

[array([ 0,  2,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17,
       16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), array([ 0,  3,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 18,
       16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), array([ 0,  4,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 19,
       16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])]
[array([ 0,  2,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17,
       16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), array([ 0,  3,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 18,
       16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), array([ 0,  4,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 19,
       16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])]
[array([ 0,  1,  3,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       18, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]), array([ 0,  1,  4

In [23]:
i = 4080
for _ in range(100000):
    mult(result.u_vector[result.u_map[i]][0], result.u_vector[result.u_map[i]][0])

In [3]:
G_z = dnx.zephyr_graph(12)

num_delete = int(0.04 * G_z.number_of_nodes())
random.seed(42)
to_remove = random.sample(range(0, G_z.number_of_nodes()), num_delete)

for node in to_remove:
    G_z.remove_node(node)

# relabel nodes to be continuous
label_mapping = {list(G_z.nodes)[j]:j for j in range(G_z.number_of_nodes())}
G_z = nx.relabel_nodes(G_z, label_mapping) 

In [4]:
G_vector_zephyr = schreier_rep(G_z, num_samples=3) # takes about 3 mins #190210142896128
G_vector_zephyr.num_automorphisms

leaf nodes reached:  42
total nodes reached:  903


126806761930752

In [ ]:
126806761930752
190210142896128

In [10]:
G_vector_zephyr = schreier_rep(G_z, num_samples=1) # takes about 5 mins
G_vector_zephyr.num_automorphisms

leaf nodes reached:  44
total nodes reached:  951


190210142896128

In [9]:
G_vector_zephyr = schreier_rep(G_z, num_samples=2) # takes about 5 mins
G_vector_zephyr.num_automorphisms

leaf nodes reached:  44
total nodes reached:  945


190210142896128

In [11]:
G_vector_zephyr = schreier_rep(G_z, num_samples=4) # takes about 5 mins
G_vector_zephyr.num_automorphisms

leaf nodes reached:  42
total nodes reached:  903


190210142896128

In [12]:
G_vector_zephyr = schreier_rep(G_z, num_samples=5) # takes about 5 mins
G_vector_zephyr.num_automorphisms

leaf nodes reached:  42
total nodes reached:  903


190210142896128

In [ ]:
G_vector_zephyr = schreier_rep(G_z, num_samples=20) # takes about 5 mins
G_vector_zephyr.num_automorphisms

In [13]:
G_vector_zephyr = schreier_rep(G_z, num_samples=100) # takes about 5 mins
G_vector_zephyr.num_automorphisms

leaf nodes reached:  42
total nodes reached:  903


190210142896128

In [3]:
G_vector_zephyr = schreier_rep(G_z, num_samples=1000) # takes about 5 mins
G_vector_zephyr.num_automorphisms

leaf nodes reached:  91
total nodes reached:  1845


4076863488

smaller

In [1]:
G_z = dnx.zephyr_graph(6)

num_delete = int(0.04 * G_z.number_of_nodes())
random.seed(42)
to_remove = random.sample(range(0, G_z.number_of_nodes()), num_delete)

for node in to_remove:
    G_z.remove_node(node)

# relabel nodes to be continuous
label_mapping = {list(G_z.nodes)[j]:j for j in range(G_z.number_of_nodes())}
G_z = nx.relabel_nodes(G_z, label_mapping) 

NameError: name 'dnx' is not defined

In [9]:
G_vector_zephyr = schreier_rep(G_z, num_samples=4) # takes about 5 mins
G_vector_zephyr.num_automorphisms

leaf nodes reached:  566
total nodes reached:  6543


2567836929097728